### ISSUE TITLE
Module submission: ViPER4Android Magisk v14 module

### ISSUE THREAD

**Issue by ShadySquirrel** [topjohnwu/Magisk_Repo_Central#105]
https://github.com/ShadySquirrel/ViPER4Android

It's based on your code from original V4A module, adjusted for ~~v4 (and v5 template in another branch)~~ template 1400, but I've used different id to make sure they won't clash. Other versions are available under releases and their respective branches.

EDIT: updated for new module template.

**Comment by topjohnwu** [comment]
@ShadySquirrel thanks, I will remove my version

**Comment by ShadySquirrel** [comment]
Thank you :)
