### ISSUE TITLE
Xposed Magisk SDK25

### ISSUE THREAD

**Issue by ErnyTech** [topjohnwu/Magisk_Repo_Central#107]
Xposed Magisk Module for all Arch (arm, arm64, x86) SDK25
Github repo: https://github.com/PurifyOS/Xposed-magisk-sdk25.git
Please add It :-)

**Comment by TheComputerGuy96** [comment]
@ErnyTech Your module link is broken

_Sent from my Samsung GT-S7580 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ErnyTech** [comment]
Link work..

**Comment by topjohnwu** [comment]
@ErnyTech I added you as a collab in my Xposed repo for SDK 24 and 25, you can update binaries directly. If you run into any issues regarding scripting, please notify me and I'll fix it
