### ISSUE TITLE
AirAudio Magisk-Module

### ISSUE THREAD

**Issue by funtax** [topjohnwu/Magisk_Repo_Central#112]
Hey there,

would you please clone this into your space:
https://github.com/funtax/airaudio-magisk-module

It's a module to enable the "system-mode" in the app "AirAudio".
It's used via zip-files since a long time, but now it's updated to the new Magisk-version and finally on Github :)

**Comment by topjohnwu** [comment]
Please update your template and re-submit, thanks!
