### ISSUE TITLE
Seeder (entropy) for Magisk.... To free Your phone from lags.

### ISSUE THREAD

**Issue by koko115** [topjohnwu/Magisk_Repo_Central#113]
ID=Seeder

https://github.com/koko115/Seeder.git

Seeder (entropy) for Magisk

This module is for Magisk 13.1 + v4 template.

This mod give more entropy, for better and smoth runing, with no lag.

After install go to console type "su" then "entro"

I test it on Galaxy S8+ sdk 24 (7.0) and Note Pro 12.2 sdk 20 (5.0)

Stock entropy was +-400 now is +-4000

Module also stop working when screen is off.

Regards 

_Sent from my Samsung SM-G955F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by topjohnwu** [comment]
Please update your template version and re-submit, thanks!
