### ISSUE TITLE
mBEDed-Exo-2-font

### ISSUE THREAD

**Issue by mBEDed** [topjohnwu/Magisk_Repo_Central#116]
I have created a module to install Exo 2 Font to Android (5.0+). This is first time i have created somting like this also i'm new to github as i am basically from electronics field so do guide me if there is any error. Thanks.

https://github.com/mBEDed/Systemlessly-Exo-2-Font-by-mBEDed

**Comment by topjohnwu** [comment]
Please update your template module and re-submit!
