### ISSUE TITLE
https://github.com/songyanzhi/NFC-SIM-Enabler-for-Xiaomi

### ISSUE THREAD

**Issue by songyanzhi** [topjohnwu/Magisk_Repo_Central#119]
https://github.com/songyanzhi/NFC-SIM-Enabler-for-Xiaomi

**Comment by songyanzhi** [comment]
抱歉，是這個
https://github.com/songyanzhi/NFC-SIM-Enabler-for-Xiaomi

**Comment by topjohnwu** [comment]
Please update your template module and re-submit!
