### ISSUE TITLE
[Module Submission - V3 template] IOS 10 Emojis

### ISSUE THREAD

**Issue by blake1029384756** [topjohnwu/Magisk_Repo_Central#12]
https://github.com/blake1029384756/IOS-10-Emoji-Magisk

I updated the link since i changed it

**Comment by Nishidh25** [comment]
gi

**Comment by blake1029384756** [comment]
I have update the template to v2

**Comment by blake1029384756** [comment]
I have updated the template to v3

**Comment by jplwolters** [comment]
Its just a copy of my repo: https://github.com/jplwolters/magisk-module-iOS10-Emoji
What I did: https://github.com/jplwolters/Magisk-ios10-Emoji-font/commit/790bcd286a368d945fa318d67ce0729bc22e2c15
what @blake1029384756 did after: https://github.com/blake1029384756/IOS-10-Emoji-Magisk/commit/affe87d480567941dff4eb2e487aacafd42090a0

**Comment by blake1029384756** [comment]
@jplwolters  that pic is the only thing I took because it was more detailed than the one I already had. I also asked the creator of the emoji file if i could use it and gave him the credit he deserves. I created this module all on my own, I didn't see yours until you opened an issue a hole month after I did.
