### ISSUE TITLE
[Module Submission] Mi5 Headphone Volume Fix

### ISSUE THREAD

**Issue by chhapil** [topjohnwu/Magisk_Repo_Central#123]
Mi5 Global ROM user suffer with low volume issue on headphone and headset while this issues is not present on the China ROMs or EU roms. this mod simply loads the sound config from china rom to global ROM.

Repo
https://github.com/chhapil/Mi5-Headphone-Volume-Fix

XDA thread
https://forum.xda-developers.com/mi-5/development/magisk-mi5-low-headphone-volume-fix-t3669976

Kindly approve.

**Comment by topjohnwu** [comment]
You need to have a `master` branch for submission. I added the branch for you (using your `1400` branch).

**Comment by chhapil** [comment]
Thanks
