### ISSUE TITLE
[Module Submission] Google Assistant Disabler

### ISSUE THREAD

**Issue by keeferrourke** [topjohnwu/Magisk_Repo_Central#13]
Hi there,

Please add my Magisk Module [Google Assistant Disabler](https://github.com/keeferrourke/gassist-disabler) to this repo.
It updates the build.prop to remove eligibility for Google Assistant on Pixel devices and Pixel ROMs.

Notes: Definitely not compatible with [Google Assistant Enabler](https://github.com/Magisk-Modules-Repo/Google_Assistant_Enabler), as this module does exactly the opposite operation.

Cheers,
Keefer

**Comment by keeferrourke** [comment]
@topjohnwu it's been almost 2 months? some feedback would be nice.

**Comment by jplwolters** [comment]
@keeferrourke update your template. Update it to version 4

**Comment by topjohnwu** [comment]
Sorry, modules that only changes props will not be added to the repo, as a new feature is coming to Magisk Manager soon. I will also remove those existing repos which falls in the criteria just mentioned once the new feature is out.  
However, I appreciate your effort to develop a Magisk module!

**Comment by d0k3** [comment]
Well, I don't want to nag, but even the newest Magisk Manager version does not have the build.prop editor yet, and thus @keeferrourke's module is still the only proper way of disabling the Google Assistant on Magisk. So... could this maybe be added until the Magisk Manager has build.prop editor support?

**Comment by keeferrourke** [comment]
Agreed... with no clear supported method for making prop changes within the latest versions of Magisk, I would really like to see prop mods added in the interim. My module still works if it's added manually (as far as I know), but it's a hassle, and it's not discoverable.

... I've opted to completely disable the Google app and replace it with DuckDuckGo's search, sacrificing useful features like screen-reading, etc.

**Comment by d0k3** [comment]
@keeferrourke - could you perhaps release a compiled ZIP of that module and/or give us instructions on how to install. Also, sorry for asking this here, but you seem to have disabled issues for your repo.

**Comment by keeferrourke** [comment]
I've reenabled issues. They were disabled in lieu of actually archiving the repository since I was told the module was invalid above. Now that there is actual interest in the module again, the repo is open for Issues and PRs. Feel free to contribute.
