### ISSUE TITLE
Marvel & DC bootanimation

### ISSUE THREAD

**Issue by jplwolters** [topjohnwu/Magisk_Repo_Central#130]
https://github.com/jplwolters/Magisk-Marvel-and-DC-boot-animation
A bootanimation with DC & marvel super hero's

**Comment by topjohnwu** [comment]
Sorry, but modules will not load in post-fs mode
The post-fs entry is removed from the template for a reason

**Comment by jplwolters** [comment]
sorry, in the commit I meant postfsdata mode enabled (instead of post-fs enabled) but I did that for testing but it wasn't needed. I Disabled postfsdata mode.
