### ISSUE TITLE
ViPER4Android v2.3.4.0 (super quality driver arm/arm64/x86)

### ISSUE THREAD

**Issue by sdotter** [topjohnwu/Magisk_Repo_Central#133]
Hi topjohnwu,

I've made a module: https://github.com/sdotter/ViPER4Android-v2.3.4.0
Keep up your good work!

Grtz,

Sicco

**Comment by ShadySquirrel** [comment]
Why, though? There is already V4A module with latest driver/app (I see you based your work on top of it :)) supporting all architectures, not only ARM64. Also, you've pushed bunch of QCOM specific libraries, which aren't needed there.

**Comment by sdotter** [comment]
yeah thats right.. but i wanted to have 2.3.4.0 + super quality driver.. ;)
also with the version thats already in repository.. my htc audio effects didnt work any more...so i also fixed that issue.
is it ok?

**Comment by sdotter** [comment]
i will remove qcom libs... you are right about that 👍

**Comment by sdotter** [comment]
ps: thanks for quick reply

**Comment by ShadySquirrel** [comment]
What is the issue with htc audio effects? What changes are necessary? Nobody opened a issue so far so I don't have a clue :D since I don't own HTC device.
P.S. Use the edit buton, Luke :)

**Comment by sdotter** [comment]
lol ... yeah will edit next time ;)

But issue was.. with v4a 2.5.0.5, my htc 10 has 'theater mode' or 'music mode'... both didnt work anymore after flashing existing v4a module. Also... webaudio (html5 audio) from chrome browser for example wasnt processed thru viper4android... also fixed that issue. But all for v4a 2.3.4.0 because i like this GUI better.

**Comment by ShadySquirrel** [comment]
Looks fine to me now, you'll have to wait for @topjohnwu to approve this.
