### ISSUE TITLE
injected YouTube Background Playback - Vanced

### ISSUE THREAD

**Issue by zanezam** [topjohnwu/Magisk_Repo_Central#134]
hi topjohnwu,

the iYTBP team would like to add 4 modules to the magisk repo which are:

https://github.com/zanezam/iYTBP-Vanced-black-x86-x86_64-Magisk-Repo
https://github.com/zanezam/iYTBP-Vanced-black-arm-arm64-Magisk-Repo
https://github.com/zanezam/iYTBP-Vanced-x86-x86_64-Magisk-Repo
https://github.com/zanezam/iYTBP-Vanced-arm-arm64-Magisk-Repo
these are basically all the same versions just for different arch's and themed/not themed 
variants hence 4 different modules.
more about the project itself: https://forum.xda-developers.com/android/apps-games/app-iytbp-injected-youtube-background-t3560900
a word about redundance and possible already availabale modules: these new prepared modules above will be the **official versions** which will be maintained directly by the original iYTBP team.

thx in advance
ZZ

**Comment by topjohnwu** [comment]
Could you merge your module to handle arch detection?
My template will already detect your arch provide the variable `$ARCH` for you.
By doing so you should end up with only 2 modules (themed v.s. un-themed)

I'll close the issue now, once you adjusted this please open again :)

**Comment by zanezam** [comment]
yeah will do that thank u for the tip, 2 are better than 4 :)
