### ISSUE TITLE
Blobs Forever - Get the blob emoji back in Android 8.0

### ISSUE THREAD

**Issue by bdr99** [topjohnwu/Magisk_Repo_Central#137]
In Android 8.0, Google changed the emoji, getting rid of the beloved "blobs" that many people liked. This simple module, called "Blobs Forever", changes the emoji font to get the blob emoji back in Android 8.0. If it could be added to the repo, I would greatly appreciate it. Thanks.

https://github.com/bdr99/BlobsForever

**Comment by topjohnwu** [comment]
This module does the work 100% identical to yours
https://github.com/Magisk-Modules-Repo/magisk-notocoloremoji-replacer
