### ISSUE TITLE
Documentation request: examples on util_functions.sh use in modules

### ISSUE THREAD

**Issue by stangri** [topjohnwu/Magisk_Repo_Central#142]
Hey @topjohnwu, creating an issue here seems to be the only way for module developers to reach out to you, so here it goes.

I'm struggling to get AppSystemizer properly working with the newer versions/templates of Magisk and I don't have time to study the new code, can you provide an example on how the module can make use of the util_functions.sh, specifically:

1. How to find the path where I can source the util_functions.sh file from both when the module is being flashed/installed in recovery and when module is being installed thru magisk manager?
2. How to get the full path/file name of the magisk modules image, get mounted status, mount, adjust size and unmount the image thru functions in util_functions.sh, both in recovery and when modules are being loaded?

**Comment by topjohnwu** [comment]
1. The sourcing of `util_function.sh` is already in the new template, why do you need to do it yourself? It is literally the first step in a module installation
2. The paths are never changed. For mounting and unmounting images, it is now handled by the `magisk` binary, not in any form of shell script code.

**Comment by stangri** [comment]
Are there some magisk binary commands I could use to manipulate the image then? I really need the image manipulation for the module and ever since you've moved away from shell commands to the binary it became unstable.
