### ISSUE TITLE
Unity xposed

### ISSUE THREAD

**Issue by therealahrion** [topjohnwu/Magisk_Repo_Central#147]
https://github.com/therealahrion/Xposed-Framework-Unity

Please add this to the repo

**Comment by topjohnwu** [comment]
I will skip this one, since it might confuse people which one to install (and the module will be very large and will take a long time to download)
Anyways, thanks for your contribution!

**Comment by therealahrion** [comment]
Why? It currently deletes any other Xposed Magisk and there are multiple versions of Viper4Android and Dolby Atmos that confuse people too. . .
