### ISSUE TITLE
[Module Submission] Volume Steps Increase

### ISSUE THREAD

**Issue by stangri** [topjohnwu/Magisk_Repo_Central#15]
https://github.com/stangri/Volume_Steps_Increase

**Comment by stangri** [comment]
@topjohnwu dude, it's been a month! I know you're actively developing both magisk and magisk manager, but they're nothing without the modules!

**Comment by blake1029384756** [comment]
I agree! Please update the repo

**Comment by topjohnwu** [comment]
Sorry, modules that only changes props will not be added to the repo, as a new feature is coming to Magisk Manager soon. I will also remove those existing repos which falls in the criteria just mentioned once the new feature is out.  
However, I appreciate your effort to develop a Magisk module!
