### ISSUE TITLE
Module: Full resolution upload in Google Photos

### ISSUE THREAD

**Issue by SantiagoPintos** [topjohnwu/Magisk_Repo_Central#151]
This module enables full resolution upload in Google Photos adding "nexus.xml" in /system/etc/sysconfig

- https://github.com/SantiagoPintos/Full-resolution-upload-in-Google-Photos

**Comment by topjohnwu** [comment]
I think this doesn't actually works. Google photos verify the actual photos, not only checking `nexus.xml`
