### ISSUE TITLE
Twemoji Module

### ISSUE THREAD

**Issue by Xyllon** [topjohnwu/Magisk_Repo_Central#153]
This module replaces system emojis with Twitter's "Twemoji".

https://github.com/Xyllon/Twemoji-systemless

**Comment by topjohnwu** [comment]
You need a `master` branch to submit to the repo. Please refer to the official docs for more info.
Re-open this after you've fixed it

**Comment by Xyllon** [comment]
Sorry my bad, still kinda new to this whole Git thing. Should be good now.
