### ISSUE TITLE
Sudo4Droid Magisk Module

### ISSUE THREAD

**Issue by PorygonZRocks** [topjohnwu/Magisk_Repo_Central#161]
This module adds a sudo command (it's just a script calling su -c). The repo is at https://gitlab.com/PorygonZRocks/sudo4droid-magisk. If it needs to be GitHub, let me know and I'll transfer it over.

**Comment by topjohnwu** [comment]
I do not have permission to view it

**Comment by PorygonZRocks** [comment]
Sorry about that, set as public now.
