### ISSUE TITLE
Module missing from Magisk Manager online repo

### ISSUE THREAD

**Issue by crok** [topjohnwu/Magisk_Repo_Central#175]
Hi,

Some users and I just noticed, that [my module](https://github.com/crok/crokrammgmtfix) is no longer available in the Magisk Manager app but it is listed in the [Magisk Repo Central](https://github.com/topjohnwu/Magisk_Repo_Central) (almost the last one). May I know the reason? What should I do to make it available in Magisk Manager again?

Sincerely,
____
crok

**Comment by Didgeridoohan** [comment]
Update it to the latest template.

**Comment by crok** [comment]
Last template commit was on 6th Sept and my module is online since 31st Oct - the only thing in my template that is not the same is the template number (it was 4, now it is 1400 but it worked like a charm anyway). I updated the files. So, what is the next step for me?

**Comment by Didgeridoohan** [comment]
If you've updated the module to the latest template, make sure to also update the template version in module.prop...

**Comment by crok** [comment]
Yes, sure, done.

**Comment by crok** [comment]
Seems it is available again - thank you!
