### ISSUE TITLE
Module submission: App Systemizer

### ISSUE THREAD

**Issue by stangri** [topjohnwu/Magisk_Repo_Central#2]
Hey @topjohnwu please include the linked module: https://github.com/stangri/AppSystemizer

**Comment by stangri** [comment]
Actually, can you have a look at it? This module worked just fine in v9 and even in the v10 snapshots, with v10 it causes constant crashes of Google Play Services. I've updated it to the latest template, but it didn't help!
![screenshot_20170102-145235](https://cloud.githubusercontent.com/assets/4768176/21597345/718357b0-d0fe-11e6-8b41-65cb554026b9.png)

**Comment by topjohnwu** [comment]
@stangri does it happen all the time? Also, does it only effect this module?
If there is an issue in v10, I'd like to fix it, thanks!

**Comment by stangri** [comment]
@topjohnwu for me -- yes, it's the only module which is giving me grief. I got a suggestion from XDA to uninstall Play Services updates, clear its cache, reboot and reinstall updates to get rid of the error, but I kinda fumbled play services removal, so I'm reinstalling Nougat from scratch atm. :(
BTW, others reported the problem even without my module, check the last two messages here: https://forum.xda-developers.com/apps/magisk/module-app-systemizer-t3477512/post70367003#post70367003

**Comment by topjohnwu** [comment]
@stangri , I think it's a Magisk v10 issue, I'll release fix ASAP
