### ISSUE TITLE
{Awesome Module Submission}Op3/3t AccentOS Colours

### ISSUE THREAD

**Issue by Nishidh25** [topjohnwu/Magisk_Repo_Central#20]
https://github.com/Nishidh25/Op3-3t-AccentOS-Colours
 
Here is the screenshot of the mod

https://forum.xda-developers.com/devdb/project/?id=19498#screenshots
Only some are ss others are extras

 and u can read the Readme.md for info

I have been working on this for 2 months 
Hope u add clone this to your repo
Thanks for making magisk @topjohnwu

**Comment by topjohnwu** [comment]
Sorry for the late reply, please update your module with template v3, thanks!

**Comment by topjohnwu** [comment]
Please update to template v4, and open a new issue for request, thanks!
