### ISSUE TITLE
[Module Submission v3 template] ViPER4Android FX

### ISSUE THREAD

**Issue by therealahrion** [topjohnwu/Magisk_Repo_Central#27]
https://github.com/therealahrion/ViPER4Android-FX

This installs the ViPER4Android FX as well as installs my Audio Modification Library to allow multiple audio mods to work seamlessly with one another on Magisk.

This is a unified Magisk/System installer that takes advantage of magisk_module_template_v3

**Comment by therealahrion** [comment]
updated to template v3

**Comment by topjohnwu** [comment]
Please update to template v4, and open a new issue for request, thanks!
