### ISSUE TITLE
Universal Kernel Manager

### ISSUE THREAD

**Issue by yarpiin** [topjohnwu/Magisk_Repo_Central#31]
Hi Can you add UKM to Magisk 
Regards 
Slawek

https://github.com/yarpiin/magisk-UKM.git

**Comment by topjohnwu** [comment]
The v3 template also requires module.prop to have the template version in it, please update accordingly

**Comment by yarpiin** [comment]
will do thanx

**Comment by yarpiin** [comment]
Hi module.prop updated
