### ISSUE TITLE
[Module Submission] Hardware Key Disabler (LOS)

### ISSUE THREAD

**Issue by GongJianwei** [topjohnwu/Magisk_Repo_Central#36]
Disable hardware key on Lineage OS or CyanogenMod devices.
https://github.com/GongJianwei/hardware-key-disabler-los

**Comment by topjohnwu** [comment]
Please upgrade to module v3, with the template version number in the module.prop!

**Comment by GongJianwei** [comment]
I am really sure I fork the newest template. That's mean I can't delete other files like post-fs-data.sh?

**Comment by topjohnwu** [comment]
What I mean is that in the file `module.prop` in your repo, you should have a entry called `template`, as that is the info which will be used in the future
Check the `module.prop` file in the template, you'll get what I'm saying :)

**Comment by GongJianwei** [comment]
Already added, pleases check again.
