### ISSUE TITLE
Add Pixel Launcher module

### ISSUE THREAD

**Issue by miigotu** [topjohnwu/Magisk_Repo_Central#37]
Hi, not sure if there is a reason this module is not added to the repo yet, but if not could you add it please? I have been using it on my 6p for months and have no issues with it. Thanks.
https://github.com/jaimbo/PixelLauncher

(Moved from https://github.com/topjohnwu/magisk-module-template/issues/10)

**Comment by topjohnwu** [comment]
Please upgrade your module to v3, and also update the README.md
