### ISSUE TITLE
[Module Submission] Systemlessly-Font-with-Minglan-Lanting-Pro

### ISSUE THREAD

**Issue by HUMORCE** [topjohnwu/Magisk_Repo_Central#45]
https://github.com/HUMORCE/Systemlessly-Font-with-Minglan-Lanting-Pro

same as Systemlessly-Font-with-Tsukushimarugo-A-CJK-Sleek
systemlessly fonts repalces , maybe you will not pass , but onece i try
much people would like to replaces system fonts

and i want to say ,

maybe magisk module should make a choice at the time of installation(aroma like) for users(client)  to reduce the similarity of modules

**Comment by topjohnwu** [comment]
Please update to template v4, and open a new issue for request, thanks!
