### ISSUE TITLE
Repo down????

### ISSUE THREAD

**Issue by therealahrion** [topjohnwu/Magisk_Repo_Central#46]
I pushed my mods to the repo and they were approved but 2 of my mods have not posted yet.  When I updated my existing mods they update, but the new ones that were approved still aren't showing up. 

This includes Dolby Atmos A7000 / Dolby Atmos Le Pro 3

**Comment by topjohnwu** [comment]
You might want to update your module template to v3.
You need to have this line in your module.prop
`template=3`

**Comment by therealahrion** [comment]
It is already updated to module template v3?

**Comment by therealahrion** [comment]
It's already there.  All the new modules you've approved arent showing
since you approved both of my Dolby Atmos.
