### ISSUE TITLE
Module submission: Speakerphone Echo Fix for Nexus 6 7.1.1

### ISSUE THREAD

**Issue by txtsd** [topjohnwu/Magisk_Repo_Central#5]
**Module name:** Speakerphone Echo Fix for Nexus 6 7.1.1
**Repo Link:** https://github.com/txtsd/magisk-module-template
**XDA Support Link:** https://forum.xda-developers.com/nexus-6/themes-apps/mod-speakerphone-echo-fix-nexus-6-t3537776/post70544279

**Comment by topjohnwu** [comment]
Sorry I missed this one so long
