### ISSUE TITLE
[Module Submission] NotoSansCJK(legacy)

### ISSUE THREAD

**Issue by simonsmh** [topjohnwu/Magisk_Repo_Central#51]
https://github.com/simonsmh/magisk-notosanscjk-legacy

**Comment by topjohnwu** [comment]
Is this duplicate with https://github.com/Magisk-Modules-Repo/magisk-notosanscjk-nougat?

**Comment by simonsmh** [comment]
Nope. This should be a low system version devices' solution, but now this repo hasn't been updated to template v4 yet.

**Comment by simonsmh** [comment]
In fact my other modules has been tested and upgraded to template v4. They works well, too. I need some extra time to bring this module up again.
Well maybe I should temporarily stop the submission?
