### ISSUE TITLE
[Module Submission] MagicGApps

### ISSUE THREAD

**Issue by VR25-xda** [topjohnwu/Magisk_Repo_Central#59]
This package is the most striped down and customizable GApps variant, lighter than the Pico GApps package itself. It's intended for those with limited /system space and tweak freaks who like to keep their stuff optimized, lightweight and easily upgradable.

Single, dynamic installer for ARM & ARM64
Core Google syncing APKs (Google Play Services, SetupWizard, Google Play Store)
sysconfig/google.xml battery saving patches
Easily upgradable/tweakable 

https://github.com/VR25-xda/MagicGApps

**Comment by topjohnwu** [comment]
@VR25-xda I added your module to the repo, but please update your module to template v4, thanks!

**Comment by VR25-xda** [comment]
I'll update all my modules to the v4 template as soon as I get a good internet connection. Right now, I have extremely limited internet access. -- Thanks 

_Sent from my Motorola XT1635-02 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
