### ISSUE TITLE
Module submission: gms-doze

### ISSUE THREAD

**Issue by simonsmh** [topjohnwu/Magisk_Repo_Central#66]
https://github.com/simonsmh/magisk-gms-doze

**Comment by topjohnwu** [comment]
@simonsmh I will close your repo for now, the original author has uploaded his original version (https://github.com/Magisk-Modules-Repo/EnableGMSModuleMagisk)

**Comment by simonsmh** [comment]
Original? What is that mean?
All things are different, please reserve both of them. Thank you.

**Comment by topjohnwu** [comment]
https://github.com/topjohnwu/Magisk_Repo_Central/issues/100
If you still want me to put your implementation on the repo, just give me your repo link again.

**Comment by simonsmh** [comment]
https://github.com/simonsmh/magisk-gms-doze

**Comment by simonsmh** [comment]
https://gitlab.com/simonsmh/magisk-gms-doze
