### ISSUE TITLE
[Module Submission] Magic Folder Binder

### ISSUE THREAD

**Issue by VR25-xda** [topjohnwu/Magisk_Repo_Central#69]
***QUICK REFERENCE***
* Automagically binds directories or even the entire internal storage to the sdcard on boot.
* Install the module, configure fbind_list.txt (located in /data/media/0/ a.k.a, internal storage), run fbind -m to move your files over to the sdcard all at once, reboot and forget!
* Target folders are created automatically.

https://github.com/VR25-xda/Magic-Folder-Binder

**Comment by topjohnwu** [comment]
Please update to template v4, and open a new issue for request, thanks!
