### ISSUE TITLE
[Module Submission] Systemless SourceHanSans and HanazonoMincho FontPackage Marshmallow Support

### ISSUE THREAD

**Issue by MoneMizuno** [topjohnwu/Magisk_Repo_Central#73]
https://github.com/MoneMizuno/systemless-shs-and-hanamin-font-package-marshmallow

Let the Android 6 Marshmallow device support Source Han Sans multiple weight display, and use HanaMin font extension Ext-B, Ext-C, Ext-D, Ext-E Chinese characters display.

**Comment by topjohnwu** [comment]
Please update to template v4, and open a new issue for request, thanks!
