### ISSUE TITLE
[Module Submission] Systemless SourceHanSans and HanazonoMincho FontPackage Nougat Support

### ISSUE THREAD

**Issue by MoneMizuno** [topjohnwu/Magisk_Repo_Central#74]
https://github.com/MoneMizuno/systemless-shs-and-hanamin-font-package-nougat

Let the Android 7 Nougat device support Source Han Sans multiple weight display, and use HanaMin font extension Ext-B, Ext-C, Ext-D, Ext-E Chinese characters display.

**Comment by topjohnwu** [comment]
Please update to template v4, and open a new issue for request, thanks!
