### ISSUE TITLE
[Module Submission]ViPER4Android FX(OnePlus3/3T Fix)

### ISSUE THREAD

**Issue by wuchjun** [topjohnwu/Magisk_Repo_Central#80]
Please add lnik:https://github.com/wuchjun/ViPER4Android-OnePlus3_3T_Fix

Magisk Module Template v3 -> v4
Update to support magisk v13+
Fix for 'Processing: No' while using Magisk on OnePlus device

**Comment by Didgeridoohan** [comment]
I would like a little bit more of an explanation what this module is about in the readme. What V4A is it supposed to fix? The official, the Magisk module in the Magisk repo, or what? 

There are functioning V4A modules out there already, that works perfectly fine on my OP3T (that, from a quick glance, does a lot of the things this module does already).

Not saying that the module isn't necessary, but some more details would be nice.

**Comment by wuchjun** [comment]
@Didgeridoohan 
1. As I said above, this module is mainly repaired "Processing:No" problem which I have seen many users asked in comminuty. After searching I found the problem caused by libvolumelistener.so. I fixed the bug by removing "volume_listener" in /vendor/etc/audio_effect.conf. 
2. With magisk updated to v13+，many comands have been merged  into one binary. I update this repo to support it.
