### ISSUE TITLE
[Module submission] Max Resolution for Youtube

### ISSUE THREAD

**Issue by DeicPro** [topjohnwu/Magisk_Repo_Central#86]
https://github.com/DeicPro/max-resolution-youtube

**Comment by the-turtle** [comment]
My module, Youtube4K_Enabler, does the same thing.

https://github.com/Magisk-Modules-Repo/YouTube4K_Enabler

**Comment by DeicPro** [comment]
I did my module before of you, check my thread

**Comment by DeicPro** [comment]
It have more clear name, YouTube4K could be misunderstood. Have better information, support thread and source of the tweak.
