### ISSUE TITLE
[Module Submission] CJK Characters Extended Support Font Package for Android Marshmallow

### ISSUE THREAD

**Issue by MoneMizuno** [topjohnwu/Magisk_Repo_Central#88]
https://github.com/MoneMizuno/Magisk-Module-CJK-Characters-Extended-Support-FontPackage-Marshmallow

Enables your device to fully support CJK character extensions and supports Unicode 10.0 text and symbols.

**Comment by Didgeridoohan** [comment]
You should be able to bake these two modules into one by keeping the two versions of the files in separate folders, named after the API version (Marshmallow=23, Nougat=24-25). Then, using the API lookup function of the template, you can simply rename the corresponding system folder to "system" and the installer will use that one.

From the template (update-binary):
```
# Detect version and architecture
api_level_arch_detect

# You can get the Android API version from $API, the CPU architecture from $ARCH
# Useful if you are creating Android version / platform dependent mods
```

Aircode suggestion to add to the update-binary, right after the Magisk image is mounted:
```
if [ $API="23" ]; then
   mv $INSTALLER/system-marshmallow $INSTALLER/system
elif [ $API="24" -o $API="25" ]; then
   mv $INSTALLER/system-nougat $INSTALLER/system
else
   abort "! Unsupported Android version!"
fi
```

Just a suggestion to keep the Magisk repo tidy.

**Comment by MoneMizuno** [comment]
Thanks for the suggestion, I try it.
Close the issue.
