### ISSUE TITLE
Remove Module from Repo

### ISSUE THREAD

**Issue by tristandesigns** [topjohnwu/Magisk_Repo_Central#91]
I don't know where to ask it, so I hope someone here can help me. Well my module adb-androidhost is on the official repo, but I want to remove it because I realized that it won't work on a lot of devices, and I recently found out that osm0sis also has a module that includes adb AND fastboot that works on more platforms. How would I remove my module from the repo?

**Comment by topjohnwu** [comment]
Sure, done
