### ISSUE TITLE
[Module submissions] osm0sis' Installers

### ISSUE THREAD

**Issue by osm0sis** [topjohnwu/Magisk_Repo_Central#98]
Not based on the module template, these support /system, /su, /magisk_merge (booted), and /magisk (recovery) installation in one zip.

https://github.com/osm0sis/adb-Installer
https://github.com/osm0sis/Adreno-Systemless-Installer
https://github.com/osm0sis/Busybox-Installer
https://github.com/osm0sis/nano-Installer
https://github.com/osm0sis/Nexus-Media-Installer

**Comment by topjohnwu** [comment]
@osm0sis open a new issue once your Nexus Media Installer is fixed :)
